// src/domain/entities/campaign.entity.ts
export class Campaign {
  constructor(
    public id: number | null,
    public title: string | null,
    public description: string | null,
    public beneficiaryName: string | null,
    public fundraisingGoal: number | null,
    public fundsRaised: number | null,
    public imageCoverUrl: string | null,
    public institution: string | null,
    public location: string | null,
    public latitude: number | null,
    public longitude: number | null,
    public numberOfContributions: number | null,
    public phoneNumber: string | null,
    public priority: number,
    public endDate: Date | null,
    public startDate: Date | null,
    public isUrgent: boolean,
    public isActivate: boolean,
    public campaignType: string | null,
    public currency: string,
    public birth: Date | null,
    public categoryId: number | null,
    public ongId: number | null,
    public userId: number | null,
    public createdAt: Date,
    public updatedAt: Date,
  ) {}
}
